--    elseif cmd == "help" then
--        print("\r\n\033[36m" .. T("help_title") .. "\033[0m")
--        print("--------------------------------------------------")
--        print(string.format("%-15s : %s", "/rooms", T("help_rooms")))
--        print(string.format("%-15s : %s", "/join [name]", T("help_join")))
--        print(string.format("%-15s : %s", "/create [name]", T("help_create")))
--        print(string.format("%-15s : %s", "/nick [name]", T("help_nick")))
--        print(string.format("%-15s : %s", "/who", T("help_who")))
--        print(string.format("%-15s : %s", "/id / /en", T("help_lang")))
--        print(string.format("%-15s : %s", "/leave", T("help_leave")))
--        print(string.format("%-15s : %s", "/exit", T("help_exit")))
--        print("--------------------------------------------------\r\n")
return function()
    print("V2" .. T("help_title") .. "V2")
    print("--------------------------------------------------")
    print(string.format("%-15s : %s", "/rooms", T("help_rooms")))
    print(string.format("%-15s : %s", "/join [name]", T("help_join")))
    print(string.format("%-15s : %s", "/create [name]", T("help_create")))
    print(string.format("%-15s : %s", "/nick [name]", T("help_nick")))
    print(string.format("%-15s : %s", "/who", T("help_who")))
    print(string.format("%-15s : %s", "/id / /en", T("help_lang")))
    print(string.format("%-15s : %s", "/leave", T("help_leave")))
    print(string.format("%-15s : %s", "/exit", T("help_exit")))
    print("--------------------------------------------------\r\n")
end
